---

- name: Install apt Dependencies
  apt:
    name: "{{ ddclient_apt_install }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  become: true

- name: Check ddclient path
  stat:
    path: "{{ddclient_path}}"
  loop:
    - /usr/bin/ddclient
    - /usr/sbin/ddclient
  loop_control:
    loop_var: ddclient_path
  register: bin_ddclient

- name: Get path
  set_fact:
    ddclient_exec: "{{ bin_ddclient.results | json_query('[?stat.exists].ddclient_path') | first() }}"

- name: Create /etc and /var/cache Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - "{{ ddclient_file.directory }}"
    - "{{ ddclient_cache }}"
    - "{{ ddclient_pid.directory }}"
  become: true

- name: Create Systemd File
  template:
    src: "ddclient.service.j2"
    dest: "/etc/systemd/system/ddclient.service"
    owner: root
    group: root
    mode: 0644
  become: true
  register: ddclient_service_result

