---
# ddclient/tasks/main.yml

- import_tasks: install.yml

- name: Build Out ddclient.conf File
  template:
    src: ddclient.conf.j2
    dest: "{{ ddclient_file.directory }}/{{ ddclient_file.file }}"
    owner: root
    group: root
  become: true
  #notify: Restart DDClient

- name: Update Mode for New Files
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    state: file
  with_items:
    - { path: "{{ ddclient_file.directory }}/{{ ddclient_file.file }}", mode: "0700" }
    - { path: "{{ ddclient_exec }}", mode: "0775" }
  become: true

- name: Autostart DDClient Block
  block:
    - name: Autostart DDClient
      service:
        name: ddclient
        enabled: yes
        state: started
      ignore_errors: true
  rescue:
    - name: Show Output of Failed Service
      shell: 'ddclient -daemon=0 -debug -verbose -noquiet'
      register: _ddclient_systemd
    - debug: var=_ddclient_systemd
